# Copyright 2025 Google LLC
# Licensed under the Apache License, Version 2.0

steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '${_REPO_NAME}/${_SERVICE_NAME}:${SHORT_SHA}', '.']
    dir: frontend

  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_REPO_NAME}/${_SERVICE_NAME}:${SHORT_SHA}']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - '${_REPO_NAME}/${_SERVICE_NAME}:${SHORT_SHA}'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'

images:
  - '${_REPO_NAME}/${_SERVICE_NAME}:${SHORT_SHA}'
\noptions:\n  logging: CLOUD_LOGGING_ONLY
